package com.forzafootball.assignment.dbdata.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TEAM_DB".
 */
@Entity
public class TeamDB {

    @Id(autoincrement = true)
    private Long id;
    private String name;
    private Boolean national;
    private String country_name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TeamDB() {
    }

    public TeamDB(Long id) {
        this.id = id;
    }

    @Generated
    public TeamDB(Long id, String name, Boolean national, String country_name) {
        this.id = id;
        this.name = name;
        this.national = national;
        this.country_name = country_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getNational() {
        return national;
    }

    public void setNational(Boolean national) {
        this.national = national;
    }

    public String getCountry_name() {
        return country_name;
    }

    public void setCountry_name(String country_name) {
        this.country_name = country_name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
